### PR TITLE
Allow users/console to add to the pot.

### PR DESCRIPTION
**Pull request by HDR**
Users with the "lottery.addpot" permission will be able to add to the pot from their own balance, using /lottery addpot

Console can add to pot using the same command.

### CODE REVIEW

**Comment by HDR** [comment]
Added a Config option and a permission

The config option allows you to set a max amount a player can deposit (does not prevent multiple smaller deposits), anyone with the permission node "lottery.admin" will bypass the max amount set in the config.

**Comment by randombyte-developer** [comment]
Thanks for the PR!

I don't quite get why somebody would add money to the pot without increasing the chance to win. But I will merge anyway. Is it ready to be merged?

**Comment by HDR** [comment]
Yep it's ready to merge.
the original intent was so admins could add to the pot, both ingame and from console, but i decided to add it so normal players can use it, if they desire to do so.

**Comment by randombyte-developer** [comment]
Ok cool.

**Pull request merged**
